# Attempting to learn from zero to hero GitHub Actions
name: Practice GitHub Action
# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  practice_job: 
    name   : Practice Job
    runs-on: ubuntu-latest
    steps  : 
      - name : Step Number 1
        run  : echo "Now starting Step 1"
        shell: bash
      - name : Checkout
        uses : action/checkout@v4
      - name : List Files
        run  : tree
